export type GlossaryEntry = { term: string; definition: string };

export const glossaryEntries: GlossaryEntry[] = [
  { term: "Appt set", definition: "A lead agreed to a calendar appointment with an agent." },
  { term: "CMA", definition: "Comparative market analysis used to price a listing using nearby sales." },
  { term: "Consent", definition: "Recorded permission to contact someone using regulated channels." },
  { term: "CRM", definition: "Customer relationship management software for contacts, tasks, and pipelines." },
  { term: "Disposition", definition: "Final outcome of a lead or deal stage." },
  { term: "Drip campaign", definition: "Automated sequence of messages over time." },
  { term: "Earnest money", definition: "Deposit showing buyer seriousness after mutual acceptance." },
  { term: "Handoff", definition: "Moving a conversation from automation to a human agent." },
  { term: "IDX", definition: "Internet data exchange feed powering listing search on websites." },
  { term: "ISA", definition: "Inside sales agent role focused on qualifying inbound leads." },
  { term: "Lead capture", definition: "Any flow that creates a new contact record from a web or ad source." },
  { term: "Lead routing", definition: "Rules that assign new leads to people or teams." },
  { term: "MLS", definition: "Multiple listing service database used by agents to publish listings." },
  { term: "Nurture", definition: "Longer-cycle follow up for leads not ready to transact immediately." },
  { term: "Pipeline", definition: "Stages a deal moves through from first contact to close." },
  { term: "Pre-approval", definition: "Lender letter estimating what a buyer can borrow." },
  { term: "Round robin", definition: "Routing pattern that distributes leads evenly across agents." },
  { term: "Smart plan", definition: "Automated workflow of tasks and messages tied to a lead lifecycle." },
  { term: "Sphere", definition: "Personal network of past clients, friends, and family." },
  { term: "Stage", definition: "Pipeline bucket like New, Nurture, or Hot." },
  { term: "Tags", definition: "Lightweight labels for segmentation and reporting." },
  { term: "TC", definition: "Transaction coordinator supporting paperwork and timelines." },
  { term: "TCPA", definition: "US telemarketing and texting regulations relevant to outreach programs." },
  { term: "Title", definition: "Company that researches ownership and issues insurance at closing." },
  { term: "Zillow Flex", definition: "Lead program naming used here as a demo source label only." },
];
